CREATE TABLE S_ROLES
(
    ID   VARCHAR(36),
    NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (NAME)
);

CREATE TABLE S_USER
(
    ID                         VARCHAR(36),
    USERNAME                   VARCHAR(100) NOT NULL,
    EMAIL                      VARCHAR(255) NOT NULL,
    ENABLED                    BOOLEAN DEFAULT TRUE,
    IS_ACCOUNT_NON_EXPIRED     BOOLEAN,
    IS_CREDENTIALS_NON_EXPIRED BOOLEAN,
    IS_ACCOUNT_NON_LOCKED      BOOLEAN,
    PRIMARY KEY (ID),
    UNIQUE (USERNAME)
);

CREATE TABLE S_PASSWORD
(
    ID               VARCHAR(36),
    CURRENT_PASSWORD VARCHAR(255) NOT NULL,
    OLD_PASSWORD     VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE S_USERS_PASSWORDS
(
    ID_USER     VARCHAR(36),
    ID_PASSWORD VARCHAR(36) NOT NULL,
    PRIMARY KEY (ID_USER, ID_PASSWORD),
    FOREIGN KEY (ID_USER) REFERENCES S_USER (ID),
    FOREIGN KEY (ID_PASSWORD) REFERENCES S_PASSWORD (ID)
);

CREATE TABLE S_PERMISSIONS
(
    ID    VARCHAR(36),
    LABEL VARCHAR(100) NOT NULL,
    VALUE VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (VALUE)
);

CREATE TABLE S_PERMISSIONS_ROLES
(
    ID_ROLE       VARCHAR(36),
    ID_PERMISSION VARCHAR(36),
    PRIMARY KEY (ID_ROLE, ID_PERMISSION),
    FOREIGN KEY (ID_ROLE) REFERENCES S_ROLES (ID),
    FOREIGN KEY (ID_PERMISSION) REFERENCES S_PERMISSIONS (ID)
);

CREATE TABLE S_USERS_ROLES
(
    ID_USER VARCHAR(36),
    ID_ROLE VARCHAR(36),
    PRIMARY KEY (ID_USER, ID_ROLE),
    FOREIGN KEY (ID_USER) REFERENCES S_USER (ID),
    FOREIGN KEY (ID_ROLE) REFERENCES S_ROLES (ID)
);
